label: Text
icon: edit_note
description: "Content component for markdown-formatted text."
structures:
  - containerBlocks
  - cardBlocks
  - splitBlocks
  - gridItemBlocks
  - accordionBlocks
  - carouselBlocks
  - contentSelectorBlocks
value:
  _component: building-blocks/core-elements/text
  text: "My text goes here."
  alignX: start
preview:
  subtext:
    - key: text
    - Add text to block
picker_preview:
  text: Text
  subtext: "A catch-all for all content types. Can contain headings, paragraphs, images, bullets."
  icon: edit_note

_inputs:
  text:
    comment: The content for the text component (Markdown format). Leave empty to use slot content instead.
    type: markdown
    options:
      bold: true
      italic: true
      link: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      undo: true
      redo: true
      format: p h1 h2 h3 h4 h5 h6
      removeformat: true
      copyformatting: true
      bulletedlist: true
      numberedlist: true
      indent: true
      outdent: true
      join_above: true
      join_below: true
      code: true
      embed: true
      horizontalrule: true
      image: true
      table: true
  alignX:
    type: select
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End
    comment: The horizontal alignment of the text component.

