label: Hidden
icon: eye-slash
description: "Hidden form field for storing data."
structures:
  - formBlocks
value:
  _component: building-blocks/forms/hidden
  name: ""
  value: ""
preview:
  text:
    - template: Hidden - {name}
  subtext: A hidden form field for storing data that should not be visible to users.
picker_preview:
  text: Hidden
  subtext: A hidden form field for storing data that should not be visible to users.
  icon: eye-slash
_inputs:
  name:
    type: text
    comment: The name attribute for the hidden input field.
  value:
    type: text
    comment: The value to be stored in the hidden field.
