collections_config:
  pages:
    path: src/content/pages
    glob:
      - "**/*.md"
    url: "/[full_slug]/"
    icon: laptop_mac
    _enabled_editors:
      - visual
    add_options:
      - name: Add New Page
        schema: default
        icon: pages
    schemas:
      default:
        name: New Page
        path: ".cloudcannon/schemas/page.md"
        remove_extra_inputs: false
    create:
      path: "[relative_base_path]/{filename|slugify|lowercase}.md"
    new_preview_url: /
    _inputs:
      title:
        type: text
        comment: Controls the metadata title for the page.

collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Data
    collections:
      - data

_structures:
  contentBlocks:
    style: modal
    id_key: _bookshop_name
    values: [] # Must contain a values array, but the structures are defined by Bookshop so there's nothing to add in here

_select_data:
  icons:
    - id: academic-cap
      name: Academic Cap
    - id: adjustments-horizontal
      name: Adjustments Horizontal
    - id: adjustments-vertical
      name: Adjustments Vertical
    - id: archive-box
      name: Archive Box
    - id: archive-box-arrow-down
      name: Archive Box Arrow Down
    - id: archive-box-x-mark
      name: Archive Box X Mark
    - id: arrow-down
      name: Arrow Down
    - id: arrow-down-circle
      name: Arrow Down Circle
    - id: arrow-down-left
      name: Arrow Down Left
    - id: arrow-down-on-square
      name: Arrow Down On Square
    - id: arrow-down-on-square-stack
      name: Arrow Down On Square Stack
    - id: arrow-down-right
      name: Arrow Down Right
    - id: arrow-down-tray
      name: Arrow Down Tray
    - id: arrow-left
      name: Arrow Left
    - id: arrow-left-circle
      name: Arrow Left Circle
    - id: arrow-left-end-on-rectangle
      name: Arrow Left End On Rectangle
    - id: arrow-left-on-rectangle
      name: Arrow Left On Rectangle
    - id: arrow-left-start-on-rectangle
      name: Arrow Left Start On Rectangle
    - id: arrow-long-down
      name: Arrow Long Down
    - id: arrow-long-left
      name: Arrow Long Left
    - id: arrow-long-right
      name: Arrow Long Right
    - id: arrow-long-up
      name: Arrow Long Up
    - id: arrow-path
      name: Arrow Path
    - id: arrow-path-rounded-square
      name: Arrow Path Rounded Square
    - id: arrow-right
      name: Arrow Right
    - id: arrow-right-circle
      name: Arrow Right Circle
    - id: arrow-right-end-on-rectangle
      name: Arrow Right End On Rectangle
    - id: arrow-right-on-rectangle
      name: Arrow Right On Rectangle
    - id: arrow-right-start-on-rectangle
      name: Arrow Right Start On Rectangle
    - id: arrow-small-down
      name: Arrow Small Down
    - id: arrow-small-left
      name: Arrow Small Left
    - id: arrow-small-right
      name: Arrow Small Right
    - id: arrow-small-up
      name: Arrow Small Up
    - id: arrow-top-right-on-square
      name: Arrow Top Right On Square
    - id: arrow-trending-down
      name: Arrow Trending Down
    - id: arrow-trending-up
      name: Arrow Trending Up
    - id: arrow-turn-down-left
      name: Arrow Turn Down Left
    - id: arrow-turn-down-right
      name: Arrow Turn Down Right
    - id: arrow-turn-left-down
      name: Arrow Turn Left Down
    - id: arrow-turn-left-up
      name: Arrow Turn Left Up
    - id: arrow-turn-right-down
      name: Arrow Turn Right Down
    - id: arrow-turn-right-up
      name: Arrow Turn Right Up
    - id: arrow-turn-up-left
      name: Arrow Turn Up Left
    - id: arrow-turn-up-right
      name: Arrow Turn Up Right
    - id: arrow-up
      name: Arrow Up
    - id: arrow-up-circle
      name: Arrow Up Circle
    - id: arrow-up-left
      name: Arrow Up Left
    - id: arrow-up-on-square
      name: Arrow Up On Square
    - id: arrow-up-on-square-stack
      name: Arrow Up On Square Stack
    - id: arrow-up-right
      name: Arrow Up Right
    - id: arrow-up-tray
      name: Arrow Up Tray
    - id: arrow-uturn-down
      name: Arrow Uturn Down
    - id: arrow-uturn-left
      name: Arrow Uturn Left
    - id: arrow-uturn-right
      name: Arrow Uturn Right
    - id: arrow-uturn-up
      name: Arrow Uturn Up
    - id: arrows-pointing-in
      name: Arrows Pointing In
    - id: arrows-pointing-out
      name: Arrows Pointing Out
    - id: arrows-right-left
      name: Arrows Right Left
    - id: arrows-up-down
      name: Arrows Up Down
    - id: at-symbol
      name: At Symbol
    - id: backspace
      name: Backspace
    - id: backward
      name: Backward
    - id: banknotes
      name: Banknotes
    - id: bars-2
      name: Bars 2
    - id: bars-3
      name: Bars 3
    - id: bars-3-bottom-left
      name: Bars 3 Bottom Left
    - id: bars-3-bottom-right
      name: Bars 3 Bottom Right
    - id: bars-3-center-left
      name: Bars 3 Center Left
    - id: bars-4
      name: Bars 4
    - id: bars-arrow-down
      name: Bars Arrow Down
    - id: bars-arrow-up
      name: Bars Arrow Up
    - id: battery-0
      name: Battery 0
    - id: battery-100
      name: Battery 100
    - id: battery-50
      name: Battery 50
    - id: beaker
      name: Beaker
    - id: bell
      name: Bell
    - id: bell-alert
      name: Bell Alert
    - id: bell-slash
      name: Bell Slash
    - id: bell-snooze
      name: Bell Snooze
    - id: bluesky
      name: Bluesky
    - id: bold
      name: Bold
    - id: bolt
      name: Bolt
    - id: bolt-slash
      name: Bolt Slash
    - id: book-open
      name: Book Open
    - id: bookmark
      name: Bookmark
    - id: bookmark-slash
      name: Bookmark Slash
    - id: bookmark-square
      name: Bookmark Square
    - id: briefcase
      name: Briefcase
    - id: bug-ant
      name: Bug Ant
    - id: building-library
      name: Building Library
    - id: building-office
      name: Building Office
    - id: building-office-2
      name: Building Office 2
    - id: building-storefront
      name: Building Storefront
    - id: cake
      name: Cake
    - id: calculator
      name: Calculator
    - id: calendar
      name: Calendar
    - id: calendar-date-range
      name: Calendar Date Range
    - id: calendar-days
      name: Calendar Days
    - id: camera
      name: Camera
    - id: chart-bar
      name: Chart Bar
    - id: chart-bar-square
      name: Chart Bar Square
    - id: chart-pie
      name: Chart Pie
    - id: chat-bubble-bottom-center
      name: Chat Bubble Bottom Center
    - id: chat-bubble-bottom-center-text
      name: Chat Bubble Bottom Center Text
    - id: chat-bubble-left
      name: Chat Bubble Left
    - id: chat-bubble-left-ellipsis
      name: Chat Bubble Left Ellipsis
    - id: chat-bubble-left-right
      name: Chat Bubble Left Right
    - id: chat-bubble-oval-left
      name: Chat Bubble Oval Left
    - id: chat-bubble-oval-left-ellipsis
      name: Chat Bubble Oval Left Ellipsis
    - id: check
      name: Check
    - id: check-badge
      name: Check Badge
    - id: check-circle
      name: Check Circle
    - id: chevron-double-down
      name: Chevron Double Down
    - id: chevron-double-left
      name: Chevron Double Left
    - id: chevron-double-right
      name: Chevron Double Right
    - id: chevron-double-up
      name: Chevron Double Up
    - id: chevron-down
      name: Chevron Down
    - id: chevron-left
      name: Chevron Left
    - id: chevron-right
      name: Chevron Right
    - id: chevron-up
      name: Chevron Up
    - id: chevron-up-down
      name: Chevron Up Down
    - id: circle-stack
      name: Circle Stack
    - id: clipboard
      name: Clipboard
    - id: clipboard-document
      name: Clipboard Document
    - id: clipboard-document-check
      name: Clipboard Document Check
    - id: clipboard-document-list
      name: Clipboard Document List
    - id: clock
      name: Clock
    - id: cloud
      name: Cloud
    - id: cloud-arrow-down
      name: Cloud Arrow Down
    - id: cloud-arrow-up
      name: Cloud Arrow Up
    - id: code-bracket
      name: Code Bracket
    - id: code-bracket-square
      name: Code Bracket Square
    - id: cog
      name: Cog
    - id: cog-6-tooth
      name: Cog 6 Tooth
    - id: cog-8-tooth
      name: Cog 8 Tooth
    - id: command-line
      name: Command Line
    - id: computer-desktop
      name: Computer Desktop
    - id: cpu-chip
      name: Cpu Chip
    - id: credit-card
      name: Credit Card
    - id: cube
      name: Cube
    - id: cube-transparent
      name: Cube Transparent
    - id: currency-bangladeshi
      name: Currency Bangladeshi
    - id: currency-dollar
      name: Currency Dollar
    - id: currency-euro
      name: Currency Euro
    - id: currency-pound
      name: Currency Pound
    - id: currency-rupee
      name: Currency Rupee
    - id: currency-yen
      name: Currency Yen
    - id: cursor-arrow-rays
      name: Cursor Arrow Rays
    - id: cursor-arrow-ripple
      name: Cursor Arrow Ripple
    - id: device-phone-mobile
      name: Device Phone Mobile
    - id: device-tablet
      name: Device Tablet
    - id: discord
      name: Discord
    - id: divide
      name: Divide
    - id: document
      name: Document
    - id: document-arrow-down
      name: Document Arrow Down
    - id: document-arrow-up
      name: Document Arrow Up
    - id: document-chart-bar
      name: Document Chart Bar
    - id: document-check
      name: Document Check
    - id: document-currency-bangladeshi
      name: Document Currency Bangladeshi
    - id: document-currency-dollar
      name: Document Currency Dollar
    - id: document-currency-euro
      name: Document Currency Euro
    - id: document-currency-pound
      name: Document Currency Pound
    - id: document-currency-rupee
      name: Document Currency Rupee
    - id: document-currency-yen
      name: Document Currency Yen
    - id: document-duplicate
      name: Document Duplicate
    - id: document-magnifying-glass
      name: Document Magnifying Glass
    - id: document-minus
      name: Document Minus
    - id: document-plus
      name: Document Plus
    - id: document-text
      name: Document Text
    - id: ellipsis-horizontal
      name: Ellipsis Horizontal
    - id: ellipsis-horizontal-circle
      name: Ellipsis Horizontal Circle
    - id: ellipsis-vertical
      name: Ellipsis Vertical
    - id: envelope
      name: Envelope
    - id: envelope-open
      name: Envelope Open
    - id: equals
      name: Equals
    - id: exclamation-circle
      name: Exclamation Circle
    - id: exclamation-triangle
      name: Exclamation Triangle
    - id: eye
      name: Eye
    - id: eye-dropper
      name: Eye Dropper
    - id: eye-slash
      name: Eye Slash
    - id: face-frown
      name: Face Frown
    - id: face-smile
      name: Face Smile
    - id: film
      name: Film
    - id: finger-print
      name: Finger Print
    - id: fire
      name: Fire
    - id: flag
      name: Flag
    - id: folder
      name: Folder
    - id: folder-arrow-down
      name: Folder Arrow Down
    - id: folder-minus
      name: Folder Minus
    - id: folder-open
      name: Folder Open
    - id: folder-plus
      name: Folder Plus
    - id: forward
      name: Forward
    - id: funnel
      name: Funnel
    - id: gif
      name: Gif
    - id: gift
      name: Gift
    - id: gift-top
      name: Gift Top
    - id: globe-alt
      name: Globe Alt
    - id: globe-americas
      name: Globe Americas
    - id: globe-asia-australia
      name: Globe Asia Australia
    - id: globe-europe-africa
      name: Globe Europe Africa
    - id: h1
      name: H1
    - id: h2
      name: H2
    - id: h3
      name: H3
    - id: hand-raised
      name: Hand Raised
    - id: hand-thumb-down
      name: Hand Thumb Down
    - id: hand-thumb-up
      name: Hand Thumb Up
    - id: hashtag
      name: Hashtag
    - id: heart
      name: Heart
    - id: home
      name: Home
    - id: home-modern
      name: Home Modern
    - id: identification
      name: Identification
    - id: inbox
      name: Inbox
    - id: inbox-arrow-down
      name: Inbox Arrow Down
    - id: inbox-stack
      name: Inbox Stack
    - id: information-circle
      name: Information Circle
    - id: italic
      name: Italic
    - id: key
      name: Key
    - id: language
      name: Language
    - id: lifebuoy
      name: Lifebuoy
    - id: light-bulb
      name: Light Bulb
    - id: link
      name: Link
    - id: link-slash
      name: Link Slash
    - id: list-bullet
      name: List Bullet
    - id: lock-closed
      name: Lock Closed
    - id: lock-open
      name: Lock Open
    - id: ltr
      name: Ltr
    - id: magnifying-glass
      name: Magnifying Glass
    - id: magnifying-glass-circle
      name: Magnifying Glass Circle
    - id: magnifying-glass-minus
      name: Magnifying Glass Minus
    - id: magnifying-glass-plus
      name: Magnifying Glass Plus
    - id: map
      name: Map
    - id: map-pin
      name: Map Pin
    - id: megaphone
      name: Megaphone
    - id: microphone
      name: Microphone
    - id: minus
      name: Minus
    - id: minus-circle
      name: Minus Circle
    - id: minus-small
      name: Minus Small
    - id: moon
      name: Moon
    - id: musical-note
      name: Musical Note
    - id: newspaper
      name: Newspaper
    - id: no-symbol
      name: No Symbol
    - id: numbered-list
      name: Numbered List
    - id: paint-brush
      name: Paint Brush
    - id: paper-airplane
      name: Paper Airplane
    - id: paper-clip
      name: Paper Clip
    - id: pause
      name: Pause
    - id: pause-circle
      name: Pause Circle
    - id: pencil
      name: Pencil
    - id: pencil-square
      name: Pencil Square
    - id: percent-badge
      name: Percent Badge
    - id: phone
      name: Phone
    - id: phone-arrow-down-left
      name: Phone Arrow Down Left
    - id: phone-arrow-up-right
      name: Phone Arrow Up Right
    - id: phone-x-mark
      name: Phone X Mark
    - id: photo
      name: Photo
    - id: play
      name: Play
    - id: play-circle
      name: Play Circle
    - id: play-pause
      name: Play Pause
    - id: plus
      name: Plus
    - id: plus-circle
      name: Plus Circle
    - id: plus-small
      name: Plus Small
    - id: power
      name: Power
    - id: presentation-chart-bar
      name: Presentation Chart Bar
    - id: presentation-chart-line
      name: Presentation Chart Line
    - id: printer
      name: Printer
    - id: puzzle-piece
      name: Puzzle Piece
    - id: qr-code
      name: Qr Code
    - id: question-mark-circle
      name: Question Mark Circle
    - id: queue-list
      name: Queue List
    - id: radio
      name: Radio
    - id: receipt-percent
      name: Receipt Percent
    - id: receipt-refund
      name: Receipt Refund
    - id: rectangle-group
      name: Rectangle Group
    - id: rectangle-stack
      name: Rectangle Stack
    - id: rocket-launch
      name: Rocket Launch
    - id: rss
      name: Rss
    - id: rtl
      name: Rtl
    - id: scale
      name: Scale
    - id: scissors
      name: Scissors
    - id: server
      name: Server
    - id: server-stack
      name: Server Stack
    - id: share
      name: Share
    - id: shield-check
      name: Shield Check
    - id: shield-exclamation
      name: Shield Exclamation
    - id: shopping-bag
      name: Shopping Bag
    - id: shopping-cart
      name: Shopping Cart
    - id: signal
      name: Signal
    - id: signal-slash
      name: Signal Slash
    - id: slash
      name: Slash
    - id: social/bluesky
      name: Social/bluesky
    - id: social/discord
      name: Social/discord
    - id: social/facebook
      name: Social/facebook
    - id: social/github
      name: Social/github
    - id: social/gitlab
      name: Social/gitlab
    - id: social/gitter
      name: Social/gitter
    - id: social/google
      name: Social/google
    - id: social/instagram
      name: Social/instagram
    - id: social/linkedin
      name: Social/linkedin
    - id: social/medium
      name: Social/medium
    - id: social/pinterest
      name: Social/pinterest
    - id: social/reddit
      name: Social/reddit
    - id: social/tiktok
      name: Social/tiktok
    - id: social/twitch
      name: Social/twitch
    - id: social/x
      name: Social/x
    - id: social/yelp
      name: Social/yelp
    - id: social/youtube
      name: Social/youtube
    - id: sparkles
      name: Sparkles
    - id: speaker-wave
      name: Speaker Wave
    - id: speaker-x-mark
      name: Speaker X Mark
    - id: square-2-stack
      name: Square 2 Stack
    - id: square-3-stack-3d
      name: Square 3 Stack 3d
    - id: squares-2x2
      name: Squares 2x2
    - id: squares-plus
      name: Squares Plus
    - id: star
      name: Star
    - id: stop
      name: Stop
    - id: stop-circle
      name: Stop Circle
    - id: strikethrough
      name: Strikethrough
    - id: sun
      name: Sun
    - id: swatch
      name: Swatch
    - id: table-cells
      name: Table Cells
    - id: tag
      name: Tag
    - id: ticket
      name: Ticket
    - id: trash
      name: Trash
    - id: trophy
      name: Trophy
    - id: truck
      name: Truck
    - id: tv
      name: Tv
    - id: underline
      name: Underline
    - id: user
      name: User
    - id: user-circle
      name: User Circle
    - id: user-group
      name: User Group
    - id: user-minus
      name: User Minus
    - id: user-plus
      name: User Plus
    - id: users
      name: Users
    - id: variable
      name: Variable
    - id: video-camera
      name: Video Camera
    - id: video-camera-slash
      name: Video Camera Slash
    - id: view-columns
      name: View Columns
    - id: viewfinder-circle
      name: Viewfinder Circle
    - id: wallet
      name: Wallet
    - id: wifi
      name: Wifi
    - id: window
      name: Window
    - id: wrench
      name: Wrench
    - id: wrench-screwdriver
      name: Wrench Screwdriver
    - id: x-circle
      name: X Circle
    - id: x-mark
      name: X Mark
