label: Icon
icon: star
description: "SVG icon component."
structures:
  - containerBlocks
  - cardBlocks
  - splitBlocks
  - gridItemBlocks
  - accordionBlocks
  - carouselBlocks
  - contentSelectorBlocks
value:
  _component: elements/icon
  name: "bolt"
  size: lg
  color: default
  background: true
  alignX: start
preview:
  text: Icon
  icon: star
picker_preview:
  text: Icon
  subtext: "Displays an icon from your icon library."
  icon: star

_inputs:
  name:
    type: select
    comment: The name of the icon to display from the icon library.
    options:
      values: _select_data.icons
      preview:
        text:
          - key: name
        image:
          - template: "src/icons/{id}.svg"
  size:
    type: select
    comment: The size of the icon.
    options:
      values:
        - id: none
          name: None
        - id: sm
          name: Small
        - id: md
          name: Medium
        - id: lg
          name: Large
        - id: xl
          name: Extra Large
        - id: 2xl
          name: 2xl Large
        - id: 3xl
          name: 3xl Large
  color:
    type: select
    comment: The color of the icon.
    options:
      values:
        - id: default
          name: Default (inherit)
        - id: blue
          name: Blue
        - id: green
          name: Green
        - id: yellow
          name: Yellow
        - id: orange
          name: Orange
        - id: red
          name: Red
        - id: purple
          name: Purple
        - id: pink
          name: Pink
        - id: cyan
          name: Cyan
  background:
    type: switch
    comment: Show a background behind the icon.
  inline:
    type: switch
    comment: Display the icon inline instead of block.
  alignX:
    type: select
    comment: Horizontal alignment of the icon.
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End
