label: Definition List
icon: dns
description: "Lists term/definition pairs for structured content."
structures:
  - containerBlocks
  - cardBlocks
  - splitBlocks
  - gridItemBlocks
  - accordionBlocks
  - carouselBlocks
  - contentSelectorBlocks
value:
  _component: building-blocks/core-elements/definition-list
  items: []
  alignX: start
preview:
  subtext:
    - template: "Contains {items|array_length} list {'item'|pluralize=items}"
    - Add definition list items
picker_preview:
  text: Definition List
  subtext: "For displaying key-value pairs. Ideal for glossaries, opening times, etc."
  icon: dns

_inputs:
  items:
    type: array
    label: List Items
    options:
      structures: _structures.definitionListItems
  alignX:
    type: select
    comment: The horizontal alignment of the definition list items.
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End

_structures:
  definitionListItems:
    values:
      - label: Definition List Item
        value:
          title: ""
          text: ""
        preview:
          icon: list
          text:
            - key: title
            - Definition List Item
          subtext:
            - key: text
        _inputs:
          title:
            type: text
            comment: A bolded title for the list item.
          text:
            type: textarea
            comment: The text content of the list item.
