label: Image
icon: image
description: "Optimized image component for local and remote sources."
structures:
  - containerSections
  - cardSections
  - splitSections
  - gridItemSections
  - accordionSections
  - carouselSections
  - contentSelectorSections
value:
  _component: building-blocks/core-elements/image
  source: ""
  alt: ""
  rounded: false
  aspectRatio: none
  positionVertical: center
  positionHorizontal: center
  priority: false
preview:
  icon: image
  text: Image
  subtext:
    - key: alt
    - key: source
    - Add image source
picker_preview:
  text: Image
  subtext: "Optimized image component for local and remote sources."
  icon: image

_inputs:
  source:
    type: image
    comment: The URL or path to the image.
    options:
      paths:
        uploads: src/assets/images
        static: ""
  alt:
    type: textarea
    comment: Alternative text for accessibility.
  rounded:
    type: switch
    comment: Whether to apply rounded corners to the image.
  aspectRatio:
    type: select
    comment: Set a fixed aspect ratio for the image.
    options:
      values:
        - id: none
          name: None
        - id: square
          name: Square (1:1)
        - id: landscape
          name: Landscape (4:3)
        - id: portrait
          name: Portrait (3:4)
        - id: widescreen
          name: Widescreen (16:9)
  positionVertical:
    type: select
    comment: Vertical positioning of the image within the container (if aspect ratio is set).
    options:
      values:
        - id: top
          name: Top
        - id: center
          name: Center
        - id: bottom
          name: Bottom
  positionHorizontal:
    type: select
    comment: Horizontal positioning of the image within the container (if aspect ratio is set).
    options:
      values:
        - id: left
          name: Left
        - id: center
          name: Center
        - id: right
          name: Right
  background:
    type: switch
    hidden: true
    comment: Covers the entire parent container with the image.
