label: Content Selector
icon: view_sidebar
description: "Lets users switch between different content panels using tabs."
structures:
  - containerBlocks
  - splitBlocks
  - carouselBlocks
value:
  _component: building-blocks/wrappers/content-selector
  label: ""
  items: []
  navigationPosition: start
preview:
  text:
    - key: label
    - Content Selector
  subtext:
    - template: A content selector containing {items|array_length} {"item"|pluralize=items}
    - Add items to the content selector
picker_preview:
  text: Content Selector
  subtext: Switches between related content panels using tab buttons.
  icon: view_sidebar
_inputs:
  label:
    comment: Optional label for the content selector to help identify it in the editor.
    type: text
  items:
    type: array
    options:
      structures: _structures.contentSelectorItems
  navigationPosition:
    type: select
    options:
      values:
        - id: start
          name: Start
        - id: top
          name: Top
_structures:
  contentSelectorItems:
    values:
      - label: Content Selector Item
        icon: place_item
        value:
          _component: building-blocks/wrappers/content-selector/content-selector-panel
          title: null
          contentBlocks: null
        preview:
          text:
            - key: title
            - Content Selector Item
          subtext:
            - template: A content selector item containing {contentBlocks|array_length} content {"block"|pluralize=contentBlocks}
            - Add content to the content selector item
        _inputs:
          title:
            type: text
            comment: The heading for the content panel.
          contentBlocks:
            type: array
            options:
              structures: _structures.contentSelectorBlocks
          _component:
            hidden: true
