label: Accordion
icon: expand_all
description: "Interactive component for showing and hiding content panels."
structures:
  - containerBlocks
  - cardBlocks
  - splitBlocks
  - gridItemBlocks
  - carouselBlocks
  - contentSelectorBlocks
value:
  _component: building-blocks/wrappers/accordion
  label: null
  items: []
  openFirst: false
  singleOpen: false
preview:
  text:
    - key: label
    - Accordion
  subtext:
    - template: An accordion containing {items|array_length} {"item"|pluralize=items}
    - Add items to the accordion
picker_preview:
  text: Accordion
  subtext: Hides content behind an expandable menu.
  icon: expand_all
_inputs:
  label:
    comment: Optional label for the accordion to help identify it in the editor.
    type: text
  items:
    comment: The items to display in the accordion.
    type: array
    options:
      structures: _structures.accordionItems
  openFirst:
    comment: Whether the first item will be open by default.
    type: switch
  singleOpen:
    comment: Whether only one item can be open at a time within this accordion.
    type: switch
_structures:
  accordionItems:
    values:
      - label: Item
        icon: place_item
        value:
          _component: building-blocks/wrappers/accordion/accordion-item
          title: null
          contentBlocks: null
        _inputs:
          title:
            comment: The title of the accordion item.
            type: text
          contentBlocks:
            type: array
            options:
              structures: _structures.accordionBlocks
          _component:
            hidden: true
