label: Form
icon: checklist_rtl
description: "Groups form fields into one submission area."
structures:
  - containerBlocks
  - cardBlocks
  - splitBlocks
  - gridItemBlocks
  - accordionBlocks
  - carouselBlocks
  - contentSelectorBlocks
value:
  _component: building-blocks/forms/form
  action: "./"
  formBlocks: []
preview:
  subtext:
    - template: A form containing {formBlocks|array_length} {"item"|pluralize=formBlocks}
    - Add items to the form
picker_preview:
  text: Form
  subtext: A form element that groups related form controls and handles form submission.
  icon: checklist_rtl
_inputs:
  action:
    type: url
    comment: Where to send the form-data when the form is submitted. The URL that processes the form submission.
  formBlocks:
    type: array
    comment: The form blocks to render inside the form.
    options:
      structures: _structures.formBlocks
