label: Spacer
icon: space_bar
description: "Adds adjustable spacing between content sections."
structures:
  - containerBlocks
  - cardBlocks
  - splitBlocks
  - gridItemBlocks
  - accordionBlocks
  - carouselBlocks
  - contentSelectorBlocks
value:
  _component: building-blocks/core-elements/spacer
  size: md
preview:
  text: Spacer
  icon: space_bar
picker_preview:
  text: Spacer
  subtext: "Gives space between content."
  icon: space_bar

_inputs:
  size:
    type: select
    comment: The amount of space to add.
    options:
      values:
        - id: xs
          name: Extra Small
        - id: sm
          name: Small
        - id: md
          name: Medium
        - id: lg
          name: Large
        - id: xl
          name: Extra Large
        - id: 2xl
          name: 2xl
        - id: 3xl
          name: 3xl
